#!/bin/bash

OUTPUT_FILENAME=stpuid
OPTIONS=("clean" "dev" "test" "release")

if [[ $1 == "clean" ]]; then
	rm $OUTPUT_FILENAME
	rm *.o
elif [[ $1 == "dev" ]]; then
	dmd *.d -of=$OUTPUT_FILENAME -g -debug -color
elif [[ $1 == "test" ]]; then
	dmd *.d -of=$OUTPUT_FILENAME -g -color -unittest
elif [[ $1 == "release" ]]; then
	ldc *.d -of=$OUTPUT_FILENAME -O -static
	# getting a missing lib error with GDC
else
	echo "Argument must be one of: ${OPTIONS[*]}"
	exit 1
fi
